name: VITAL_env
channels:
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - matplotlib
  - numpy
  - pandas
  - python=3.12
  - seaborn
  - ipykernel
  - requests
  - notebook  # Add Jupyter Notebook
  - jupyterlab  # Optionally add JupyterLab for a modern interface
