name: VITAL_env
channels:
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - python=3.12
  - matplotlib=3.10.6
  - numpy=2.3.3
  - pandas=2.3.2
  - scipy=1.16.2
  - seaborn
  - ipykernel
  - notebook
  - jupyterlab
  - requests=2.32.5
  - sphinx
  - sphinx-autobuild